/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/0F3mFINmvTi
 */
import Link from "next/link"
import { Input } from "src/@/components/ui/input"
import { Button } from "src/@/components/ui/button"

export function LandingPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <main className="flex-1 bg-gray-50 dark:bg-gray-900">
        <section className="w-full pt-16 md:pt-28 lg:pt-36 border-y">
          <div className="px-6 md:px-8 space-y-12 xl:space-y-20">
            <div className="grid max-w-[1400px] mx-auto gap-6 px-6 sm:px-8 md:px-12 md:grid-cols-2 md:gap-20">
              <div>
                <h1 className="lg:leading-tight text-4xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Empower Yourself with Financial Freedom
                </h1>
                <p className="mx-auto max-w-[800px] text-gray-500 md:text-xl dark:text-gray-400">
                  Join us on a journey to financial independence. Learn, grow, and achieve your financial goals.
                </p>
                <Button className="space-x-6 mt-4 mb-24 mr-4">
                  <Link
                    href="/onboarding"
                  >
                    Learn More
                  </Link>
                </Button>
                <Button className="space-x-6 mt-4 mb-24 bg-gray-800">
                  <Link
                    href="/onboarding"
                  >
                    Get Started
                  </Link>
                </Button>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-16 md:py-28 lg:py-36">
          <div className="container space-y-12 px-6 md:px-8">
            <div className="flex flex-col items-center justify-center space-y-6 text-center">
              <div className="space-y-4">
                <h2 className="text-4xl font-bold tracking-tighter sm:text-6xl">Our Key Features</h2>
                <p className="max-w-[1000px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  We provide you with the tools and resources to help you achieve financial independence.
                </p>
              </div>
            </div>
            <div className="mx-auto grid items-start gap-10 sm:max-w-5xl sm:grid-cols-2 md:gap-14 lg:max-w-6xl lg:grid-cols-3">
              <div className="grid gap-2">
                <BookOpenIcon className="h-8 w-8" />
                <h3 className="text-xl font-bold">Comprehensive Learning Materials</h3>
                <p className="text-base text-gray-500 dark:text-gray-400">
                  Access a wide range of resources to expand your financial knowledge.
                </p>
              </div>
              <div className="grid gap-2">
                <UsersIcon className="h-8 w-8" />
                <h3 className="text-xl font-bold">Community Support</h3>
                <p className="text-base text-gray-500 dark:text-gray-400">
                  Join a community of like-minded individuals on the same journey.
                </p>
              </div>
              <div className="grid gap-2">
                <CheckCircleIcon className="h-8 w-8" />
                <h3 className="text-xl font-bold">Personalized Goals</h3>
                <p className="text-base text-gray-500 dark:text-gray-400">
                  Set and track your financial goals with our personalized goal setting tools.
                </p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-16 md:py-28 lg:py-36 bg-gray-100 dark:bg-gray-800">
          <div className="container grid items-center justify-center gap-6 px-6 md:px-8">
            <div className="space-y-4">
              <h2 className="text-4xl font-bold tracking-tighter md:text-5xl/tight">Testimonials</h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Hear from our satisfied users who have achieved financial independence.
              </p>
            </div>
            <div className="mx-auto grid gap-10 sm:max-w-5xl sm:grid-cols-2 md:gap-14 lg:max-w-6xl lg:grid-cols-3">
              <div className="grid gap-2">
                <p className="text-base text-gray-500 dark:text-gray-400">
                  &quot;Project Poverty has changed my life. I&apos;ve learned so much and achieved my financial goals.&quot;
                </p>
                <p className="text-sm text-gray-500 dark:text-gray-400">- User 1</p>
              </div>
              <div className="grid gap-2">
                <p className="text-base text-gray-500 dark:text-gray-400">
                  &quot;The community support is amazing. I&apos;ve met so many like-minded individuals on the same journey.&quot;
                </p>
                <p className="text-sm text-gray-500 dark:text-gray-400">- User 2</p>
              </div>
              <div className="grid gap-2">
                <p className="text-base text-gray-500 dark:text-gray-400">
                &quot;The personalized goal setting tools are so helpful. I&apos;ve been able to track my progress and achieve
                  my goals.&quot;
                </p>
                <p className="text-sm text-gray-500 dark:text-gray-400">- User 3</p>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-16 md:py-28 lg:py-36 bg-gray-100 dark:bg-gray-800">
          <div className="container grid items-center justify-center gap-6 px-6 md:px-8">
            <div className="space-y-4">
              <h2 className="text-4xl font-bold tracking-tighter md:text-5xl/tight">Stay Updated</h2>
              <p className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                Subscribe to our newsletter for the latest updates and resources.
              </p>
            </div>
            <div className="mx-auto w-full max-w-md space-y-4">
              <form className="flex space-x-4">
                <Input className="max-w-lg flex-1" placeholder="Enter your email" type="email" />
                <Button type="submit">Subscribe</Button>
              </form>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                We respect your privacy. Unsubscribe at any time.
              </p>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}


function BookOpenIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
      <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
    </svg>
  )
}


function UsersIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}


function CheckCircleIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14" />
      <polyline points="22 4 12 14.01 9 11.01" />
    </svg>
  )
}
