/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/rcNeiK5qk7S
 */
import Link from "next/link"
import { Button } from "src/@/components/ui/button"
import { Input } from "src/@/components/ui/input"
import Logo from "~/assets/logo"

type NavigationLayoutProps = {
  children: React.ReactNode
}

const NavigationLayout:React.FC<NavigationLayoutProps> = ({children}) =>{
  return (
    <div className="flex flex-col min-h-screen">
      <header className="flex items-center justify-between h-16 px-4 md:px-6">
        <Link href="/">
         <Logo/>
        </Link>
        <nav className="hidden md:flex gap-6">
          <Link className="text-sm font-medium hover:underline" href="/">
            Home
          </Link>
          <Link className="text-sm font-medium hover:underline" href="/debt-relief">
            Debt Relief
          </Link>
          <Link className="text-sm font-medium hover:underline" href="credit-counseling">
            Credit Counseling
          </Link>
          <Link className="text-sm font-medium hover:underline" href="#">
            About Us
          </Link>
          <Link className="text-sm font-medium hover:underline" href="#">
            Contact
          </Link>
        </nav>
        <Button className="hidden md:inline-flex">Schedule a Call</Button>
      </header>
      <main className="flex-1" />
      {children}

      <footer className="grid grid-cols-1 gap-6 px-4 py-6 bg-gray-800 text-white sm:grid-cols-2 md:grid-cols-4 md:px-6">
        <div>
          <h3 className="text-sm font-semibold">Explore</h3>
          <ul className="mt-2 space-y-2">
            <li>
              <Link className="text-sm hover:underline" href="#">
                Debt Relief
              </Link>
            </li>
            <li>
              <Link className="text-sm hover:underline" href="#">
                Credit Counseling
              </Link>
            </li>
            <li>
              <Link className="text-sm hover:underline" href="#">
                About Us
              </Link>
            </li>
            <li>
              <Link className="text-sm hover:underline" href="#">
                Contact
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-sm font-semibold">Follow Us</h3>
          <ul className="mt-2 space-y-2">
            <li>
              <Link className="text-sm hover:underline" href="#">
                Facebook
              </Link>
            </li>
            <li>
              <Link className="text-sm hover:underline" href="#">
                Instagram
              </Link>
            </li>
            <li>
              <Link className="text-sm hover:underline" href="#">
                Twitter
              </Link>
            </li>
          </ul>
        </div>
        <div>
          <h3 className="text-sm font-semibold">Newsletter</h3>
          <form className="mt-2 space-y-2">
            <Input className="w-full" placeholder="Your email" type="email" />
            <Button className="w-full" type="submit">
              Subscribe
            </Button>
          </form>
        </div>
        <div>
          <p className="text-sm">© 2024 Project Poverty. All rights reserved.</p>
        </div>
      </footer>
    </div>
  )
}

export default NavigationLayout
